spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/responders
    username: root
    password: 70286_CopetS
  flyway:
    baseline-on-migrate: true

logging:
  level:
    org:
      springframework:
        web: debug
        org.hibernate: debug
  file:
    name: logs/responders.log





